### PR TITLE
chore: upgrade to pnpm 8

### PR DESCRIPTION
**Pull request by benmccann**
Fix's Brittney's error from Discord

### CODE REVIEW

**Comment by dominikg** [comment]
this is the monorepo package.json.  `@svitejs/svelte-preprocess-svg` on npm does not have this engine limitation so it should be installable with any version of pnpm

**Comment by benmccann** [comment]
Yeah. Brittney can confirm, but from the screenshot she shared, I think she was trying to contribute to this repo and was unable to because she had pnpm 8 installed. I tagged you on Discord where she was having trouble so you can see

**Comment by dominikg** [comment]
as mentioned on discord, the whole monorepo needs to be updated to use pnpm@8 (packageManager field, update lockfile at least) the engine restriction exists so that contributors don't use a different pnpm major that could lead to lockfile changes or differences in dependencies in the workspace.

**Comment by benmccann** [comment]
Ok. Bumped to pnpm 8

**Comment by dominikg** [comment]
> Ok. Bumped to pnpm 8

missing push?

**Comment by benmccann** [comment]
oops! fixed now!

**Comment by dominikg** [comment]
arf, dropping node14 from CI is probably fine at this point, bumping deps (no major updates) hopefully fixes the audit, but could require a new release for svgo.

**Comment by benmccann** [comment]
I fixed most of the audit warnings. The last two are unfixable by just upgrading packages because they're in unmaintained packages. I don't think that should block this PR since it's an issue on `main` unrelated to this which would block all PRs.

**Comment by dominikg** [comment]
thank you!!

**Pull request merged**
